### ISSUE TITLE
Move package to upstream openwrt.git

### ISSUE THREAD

**Issue by aparcar** [Hurricos/realtek-poe#23]
This seems to cover basic functionality, I don't see why this shouldn't be part of openwrt.git. I'm fine leaving the code out of it, but at least the makefile should be over there.

**Comment by mrnuke** [comment]
There's a [PR for the packages feed](https://github.com/openwrt/packages/pull/18763) already.

**Comment by mrnuke** [comment]
This package has been included in the **packages** feed for a while. Closing this issue as resolved.
