### ISSUE TITLE
Raise MAX_PORT to 48

### ISSUE THREAD

**Issue by hailfinger** [Hurricos/realtek-poe#38]
The HPE 1920-48G -PoE (JG928A) has 48 ports with PoE. With the current MAX_PORT set to 24, PoE on that switch will not work as expected.
See the discussion in https://github.com/openwrt/openwrt/pull/15763 for reference.

**Comment by Hurricos** [comment]
I actually made the openwrt/packages PR in advance, [here](https://github.com/openwrt/packages/pull/24626/commits), pointing at this HEAD.

Anyways, I've formally merged it now, and will go mess with that PR.
